# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.tracecpp <- function(x) {
    .Call('_cytoKernel_tracecpp', PACKAGE = 'cytoKernel', x)
}

.inverseLogitcpp <- function(x) {
    .Call('_cytoKernel_inverseLogitcpp', PACKAGE = 'cytoKernel', x)
}

.distKernelcpp <- function(x1, x2, rho) {
    .Call('_cytoKernel_distKernelcpp', PACKAGE = 'cytoKernel', x1, x2, rho)
}

.DEfeatures <- function(p, a) {
    .Call('_cytoKernel_DEfeatures', PACKAGE = 'cytoKernel', p, a)
}

.rowMaxcpp <- function(x) {
    .Call('_cytoKernel_rowMaxcpp', PACKAGE = 'cytoKernel', x)
}

